### ISSUE TITLE
API voor pakket aanmelden en pakket status aapassen.

### ISSUE THREAD

**Issue by Senko-rx-v2** [Eliasyoussef47/Trackr-Elias-Stephan#4]

**Comment by Senko-rx-v2** [comment]
Status opties: Aangemeld, Uitgeprint, Afgeleverd, Sorteercentrum, onderweg, afgeleverd.

**Comment by Eliasyoussef47** [comment]
adres: straatnaam huisnummer plaat postcode
naam van koper
bedrijfsnaam (webshop)
bestelnummer
besteld op: datum tijd

**Comment by Eliasyoussef47** [comment]
aanmelden werkt
